function B_sym = B(in1,lambda1)
%B
%    B_SYM = B(IN1,LAMBDA1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-May-2021 12:55:36

B_sym = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
