function B_sym = B(in1,lambda1)
%B
%    B_SYM = B(IN1,LAMBDA1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-May-2021 14:36:05

t2 = lambda1.*2.0;
t3 = -t2;
t4 = t3+1.0;
B_sym = reshape([t4,0.0,0.0,0.0,t4,0.0,0.0,0.0,t4],[3,3]);
