function f_sym = f(in1)
%F
%    F_SYM = F(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-May-2021 14:43:36

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
f_sym = (x1./2.0-1.0./2.0).*(x1-1.0)+x2.^2./2.0+x3.^2./2.0;
