function nablag_sym = nablag(in1)
%NABLAG
%    NABLAG_SYM = NABLAG(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-May-2021 14:36:05

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
nablag_sym = [x1.*-2.0;x2.*-2.0;x3.*-2.0];
