function nablalagrangian_sym = nablalagrangian(in1,lambda1)
%NABLALAGRANGIAN
%    NABLALAGRANGIAN_SYM = NABLALAGRANGIAN(IN1,LAMBDA1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-May-2021 14:36:05

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
nablalagrangian_sym = [x1-lambda1.*x1.*2.0-1.0;x2-lambda1.*x2.*2.0;x3-lambda1.*x3.*2.0];
