function nablalagrangian_sym = nablalagrangian(in1,lambda1)
%NABLALAGRANGIAN
%    NABLALAGRANGIAN_SYM = NABLALAGRANGIAN(IN1,LAMBDA1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-May-2021 12:55:36

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
nablalagrangian_sym = [lambda1+x1-1.0;x2;x3];
