function nablag_sym = nablag(in1)
%NABLAG
%    NABLAG_SYM = NABLAG(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-May-2021 12:55:36

nablag_sym = [1.0;0.0;0.0];
